### ISSUE TITLE
Cloudflare R2 BACKUP_KEEP_DAYS not woking

### ISSUE THREAD

**Issue by arima0k** [ttionya/vaultwarden-backup#134]
I noticed that the automatic deletion is not working on my Cloudflare R2 setup.

**Comment by ttionya** [comment]
Please provide relevant logs for troubleshooting.

**Comment by arima0k** [comment]
> Please provide relevant logs for troubleshooting.

How do i extract logs?

**Comment by ttionya** [comment]
`docker logs <container_id>`

**Comment by arima0k** [comment]
> `docker logs <container_id>`

https://ptero.co/cubotazysy.yaml

**Comment by ttionya** [comment]
The logs don't display any successful messages for delete. You can enter the container (`docker exec -it <container_id> bash`) and run the command `rclone lsf "BitwardenBackup:/angw" --min-age "1d"` to check if there's any output.

**Comment by arima0k** [comment]
> rclone lsf "BitwardenBackup:/angw" --min-age "1d"

No output.

**Comment by ttionya** [comment]
This tool uses the `rclone lsf "name:/path" --min-age "1d"` command to retrieve files earlier than the specified time. Since this command doesn't return, it appears that no action is taken.

This isn't an issue with this tool. If you believe it's a bug, you can provide feedback to [rclone](https://github.com/rclone/rclone).

The tool is updated promptly with new versions based on the latest rclone image after each rclone update.
