### ISSUE TITLE
关于rclone时，rclone_remote_dir的目录问题bug

### ISSUE THREAD

**Issue by TaoRone** [ttionya/vaultwarden-backup#138]
目前的rclone_remote_dir在使用时，如果末尾带了/，(即为目录)，现在的备份会直接忽略掉/，因为a和a/在s3中为两个对象
通常使用s3或者兼容s3时，没有问题
但是在使用某些对象存储时，会发生问题，因为a和a/会被识别为同一个对象，此时如果省略关键的/，会默认去寻找名为a的文件而非目录，会造成找不到该目录的bug
望修复~

**Comment by ttionya** [comment]
I'm very sorry for the late reply, I've been unwell recently and haven't had the energy to deal with issues.

The removal of the trailing slash is to solve the problem that occurred in #22.

If you encounter problems due to the absence of the trailing slash, please provide the relevant error information and the storage you are using, thank you.

非常抱歉很晚才回复你，这段时间因为生病没有精力来处理 issue。

移除最后的斜杠是为了解决 #22 出现的问题。

如果你因为末尾的斜杠的缺失而出现了问题，请提供相关的错误信息，以及使用的存储，谢谢

**Comment by TaoRone** [comment]
感谢大大的回复~~·
发现问题的第二天，已经反馈给了存储的供应商，供应商已经专门做了针对性修复~~~
现在可以识别到了
供应商名称：缤纷云
