### ISSUE TITLE
7zip do not manage utf-8 chars in password

### ISSUE THREAD

**Issue by LeChatP** [ttionya/vaultwarden-backup#147]
Hello, thank you for this tool!

Everything is in the title; I tried your repo and attempted to set a password with utf-8 chars, for example, an emoji: 👍
And everything breaks. This is because 7zip is such an old tool. It does not know how to manage utf-8. As a solution, I propose to use the `zip` tool because it works with it.

**Comment by ttionya** [comment]
Thank you for your feedback.

This tool now supports two compression formats: `7z` and `zip`. As you mentioned, even though UTF-8 passwords work fine with `zip` format, they still don't work with `7z` format (since Alpine Linux only provides [7zip](https://pkgs.alpinelinux.org/packages?name=*7z*&branch=edge&repo=&arch=&maintainer=) as a tool supporting 7z compression format).

I believe setting passwords to UTF-8 is a rare behavior, and users can create sufficiently complex passwords using a combination of numbers, letters, and special characters. It is not a necessary feature.

I prefer to maintain consistency so that people won't encounter any issues when switching `ZIP_TYPE`. Therefore, I suggest using passwords composed of ASCII characters, and this issue will not be fixed.

Thank you.
