### ISSUE TITLE
A zombie process occurs when using https ping on a URL caused by busybox wget

### ISSUE THREAD

**Issue by qianlongzt** [ttionya/vaultwarden-backup#162]
```
/data $ ps -o pid,ppid,pgid,user,stat,comm
PID   PPID  PGID  USER     STAT COMMAND
    1     0     1 1000     S    supercronic
   51     0    51 1000     S    sh
   57    51    57 1000     R    ps
/data $ wget https://google.com -o /dev/null -q
/data $ ps -o pid,ppid,pgid,user,stat,comm
PID   PPID  PGID  USER     STAT COMMAND
    1     0     1 1000     S    supercronic
   51     0    51 1000     S    sh
   59     1    58 1000     Z    ssl_client
   60     1    58 1000     Z    ssl_client
   61    51    61 1000     R    ps
```

https://github.com/spinnaker/spinnaker/issues/4479
https://github.com/qdm12/gluetun/issues/1494#issuecomment-1492879220

**Comment by ttionya** [comment]
Thank you for reporting the error and for the PR.

Initially, BusyBox's `wget` was used because it is built into Alpine and does not take up additional space. Compared to adding a `wget` dependency, I prefer to add `curl` and replace `wget` with `curl`. Curl provides comprehensive functionality and may be used in PR #161.

I will fix this issue along with PR #161, so I will close your PR for now.

Thanks again.
